# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog
  username: postgres
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: blog
  username: postgres
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: blog
  username: postgres
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
